Add question about applying Serenata to other instances
okfn-brasil/serenata-website pull request #24
Opened 2017-04-23 16:25 UTC by cuducos

Add a topic to FAQ about using Serenata source code to other instances.

2017-04-24 16:49 UTC, Irio requested changes

2017-04-24 16:49 UTC, Irio commented on faq.html
> +                <h4 class="panel-title"><a aria-controls="collapseNineteen" aria-expanded="false" class="collapsed" data-parent="#accordion" data-toggle="collapse" href="#collapseNineteen" role="butt
`páis` -> `país`

2017-04-24 19:35 UTC, cuducos commented on faq.html
> +                <h4 class="panel-title"><a aria-controls="collapseNineteen" aria-expanded="false" class="collapsed" data-parent="#accordion" data-toggle="collapse" href="#collapseNineteen" role="butt
Fixed by daa1425

2017-04-30 12:21 UTC, Irio approved these changes

2017-04-30 12:22 UTC, Irio commented
After the translation to English, we also need to add the English version of this question/answer to the `_i18n` folder. Could you please add it?

2017-05-02 14:55 UTC, jtemporal commented
>After the translation to English, we also need to add the English version of this question/answer to the _i18n folder. Could you please add it?

Isn't it already translated?

2017-05-03 00:34 UTC, cuducos commented
> Isn't it already translated?

No, when I opened the PR there was no en-US version. One of these days I'll commit something new here ; )

2017-08-22 13:06 UTC, jtemporal commented
hey @cuducos would love to merge this, can I hope for new commits and conflicts solving here? =)

2017-08-24 10:17 UTC, cuducos commented
Closed in favor of #36

2017-08-24 10:17 UTC, closed without merging